public class EstimatorConstants {
	public static final String INTEGER_DATATYPE = 'Integer';
	public static final String DATA_TYPE = 'Datatype';
	public static final String RECORD = 'Record';
	public static final String CHILDREN = '_children';
	public static final String TYPE = 'Type';

	public static final String ACTIVITYGROUP_TEMPLATES = 'Activity Group Templates';
	public static final String ACTIVITY_TEMPLATES = 'Activity Templates';
	public static final String TASK_TEMPLATES = 'Task Templates';
	public static final String TASK_PARAMETERS = 'Task Parameters';

	public static final String ACTION_ICON = 'ActionIcon';
	public static final String ICON_TYPE = 'IconType';
	public static final String ACTION_LABEL = 'Actionlabel';
	public static final String PARENT_LABEL = 'ParentLabel';

	public static final String SOBJECT_NAME = 'objectName';
	public static final String FILTER_FIELD = 'filterField';
	public static final String FILTER_CRITERIA = 'filterCriteria';
	public static final String RATE_CARD = 'rateCard';
	public static final String SEARCH_STRING = 'searchString';
	public static final String PRODUCT_RELATION = 'ProductId__r';
	public static final String PRODUCT_APINAME = 'ProductId__c';

	public static final String ACTIVITY_GROUP = 'Activity Group';
	public static final String ACTIVITY = 'Activity';
	public static final String ESTIMATE = 'Estimate';
	public static final String RESOURCE_ROLE = 'Resource Role';

	public static final String PICKLIST = 'Picklist';
}
