/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteSummary {
	public static final String SUMMARYTYPE_ROLE = 'role';
	public static final String SUMMARYTYPE_ROLE_OVERRIDE = 'role_override';
	public static final String SUMMARYTYPE_PROJECT_PHASE = 'projectPhase';
	public static final String SUMMARYTYPE_PERIOD_GROUP = 'periodGroup';
	public static final String SUMMARYTYPE_RESOURCE_TOTALS = 'resourceRoleTotals';
	public static final String SUMMARYTYPE_PROJECT_PHASE_TOTALS = 'projectPhaseTotals';
	public static final String SUMMARYTYPE_PERIOD_GROUP_TOTALS = 'periodGroupTotals';
	public static final String SUMMARYTYPE_RESOURCE_OVERRIDE_TOTALS = 'resourceRoleOverrideTotals';
}
