/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class SOQLConstants {
	public static final String BOOL_OPERATION_AND = 'AND';
	public static final String BOOL_OPERATION_OR = 'OR';
	public static final Integer SOQL_QUERY_LIMIT = 50000;
	public static final Integer QUERY_LIMIT_SMALL = 1000;
	public static final String SORT_ASC = 'ASC';
	public static final String SORT_DESC = 'DESC';
}
