public with sharing class TaskRoleSummary {
	public static final String NAME = 'TaskRoleSummary__c';
	public static final String RESOURCE_ROLE_ID = 'ResourceRoleId__c';
	public static final String ROLLEDUP_ESTIMATED_DURATION = 'RolledUpEstimatedDuration__c';
	public static final String ACTIVITY_GROUP_ID = 'ActivityGroupId__c';
	public static final String RELATED_ACTIVITY_GROUP_NAME = 'ActivityGroupId__r.Name';
	public static final String RELATED_ACTIVITY_GROUP_SEQUENCE = 'ActivityGroupId__r.Sequence__c';
	public static final String RELATED_ACTIVITY_GROUP_ESTIMATE_ID = 'ActivityGroupId__r.EstimateId__c';
	public static final String SUMMARY_LEVEL = 'SummaryLevel__c';
	public static final String ESTIMATE_ID = 'EstimateId__c';
	public static final String ESTIMATE_SUMMARY = 'Estimate';
	public static final String ACTIVITY_GROUP_SUMMARY = 'Activity Group';
}
